[package]
name = "dio"
version = "0.1.1"
authors = ["Dantezy <zhangyet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.11.4"
